# Gunakan image Node.js dari Docker Hub
FROM node:16-slim

# Tentukan direktori kerja di dalam container
WORKDIR /app

# Salin package.json dan package-lock.json ke dalam container
COPY package*.json ./

# Instal semua dependensi
RUN npm install

# Salin seluruh kode aplikasi ke dalam container
COPY . .

# Ekspos port yang akan digunakan oleh aplikasi Express
EXPOSE 8080

# Perintah untuk menjalankan aplikasi
CMD ["node", "app.js"]